#
# Makefile for Meraki drivers
#

obj-$(CONFIG_MERAKI_CONFIG) += meraki_config.o
obj-$(CONFIG_CISCO_MPS) += cisco-mps.o
obj-$(CONFIG_MERAKI_SFP_USER) += sfp_user.o
obj-$(CONFIG_MERAKI_MS420_PSU) += ms420_psu.o
obj-$(CONFIG_CISCO_ACT2) += cisco-act.o
obj-$(CONFIG_CISCO_ACT2_I2C) += cisco-act-i2c.o
obj-$(CONFIG_CISCO_ACT2_SPI) += cisco-act-spi.o
obj-$(CONFIG_CISCO_ACT2_LPC) += cisco-act-lpc.o
