#
# Makefile for Meraki drivers
#

obj-$(CONFIG_MERAKI_CONFIG) += meraki_config.o
obj-$(CONFIG_CISCO_MPS) += cisco-mps.o
obj-$(CONFIG_CISCO_RPS) += cisco-rps.o
obj-$(CONFIG_MERAKI_SFP_USER) += sfp_user.o
