#
# Makefile for Meraki drivers
#

obj-$(CONFIG_MERAKI_CONFIG) += meraki_config.o
obj-$(CONFIG_MERAKI_SFP) += sfp.o
obj-$(CONFIG_MERAKI_MS420_PSU) += ms420_psu.o
obj-$(CONFIG_MERAKI_SFP_USER) += sfp_user.o
