obj-$(CONFIG_POWER_OVER_ETHERNET)      += poe.o
poe-y                                  := poe_core.o poe_controllers.o \
                                          poe_ports.o
obj-$(CONFIG_POE_PD690XX)              += pd690xx_poe.o
obj-$(CONFIG_POE_BCM59121)             += poe_bcm59121.o
