#
# Makefile for Meraki switches
#
obj-$(CONFIG_MERAKI_MSXX) := meraki_vtss_luton26.o meraki_vtss_jaguar.o
# Luton26 boards
obj-$(CONFIG_MERAKI_MSXX) += ms220-8.o ms22_ms220-24.o
# Jaguar1 boards
obj-$(CONFIG_MERAKI_MSXX) += ms42.o ms220_48.o ms320_24.o ms320_48.o
