
obj-y := io_map.o northstar.o common.o northstar_dmu.o idm.o

obj-$(CONFIG_IPROC_PCIE) += pcie_iproc.o

obj-$(CONFIG_PM) += pm.o

obj-$(CONFIG_MACH_NS_BU) += board_bu.o flash.o
obj-$(CONFIG_MACH_MERAKI_MR26) += board_venom.o
obj-$(CONFIG_MACH_MERAKI_KINGPIN) += board_kingpin.o

obj-$(CONFIG_GPIO_IPROC) += gpio_cfg.o
