obj-$(CONFIG_SYSLINK_NOTIFY) += notifyk.o
notifyk-y := notify.o notify_driver.o  notify_init.o plat/omap_notify_setup.o  \
../notify_shmdriver/notify_shm_drv.o

#../pr_resources.o
#ccflags-y += -Wno-strict-prototypes

#Header files
ccflags-y += -Iarch/arm/plat-omap/include
ccflags-y += -Iarch/arm/plat-omap/include/syslink
