/*
 * TI814X Mux data.
 *	- Note that the mux data is same for DM385 unless mentioned in comment.
 *
 * Copyright (C) 2011 Texas Instruments Incorporated - http://www.ti.com/
 *
 * Derived from: arch/arm/mach-omap2/mux34xx.c Original copyright follows:
 *
 * Copyright (C) 2009 Nokia
 * Copyright (C) 2009 Texas Instruments
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#include <linux/module.h>
#include <linux/init.h>

#include "mux.h"

#ifdef CONFIG_OMAP_MUX

/* On J5Eco, each pin can have up to 11 functions/modes,
 * for e.g xref_clk0 has a 9th mode
 */
#define _TI814X_MUXENTRY(M0, g, m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, \
									m11) \
{									     \
	.reg_offset	= (TI814X_CONTROL_PADCONF_##M0##_OFFSET),	     \
	.gpio		= (g),						     \
	.muxnames	= { m0, m1, m2, m3, m4, m5, m6, m7, m8, m9, m10,     \
								    m11 },   \
}

/*
 * Superset of all mux modes for TI814X
 */
static struct omap_mux __initdata ti814x_muxmodes[] = {

	/* NOTE: some functional modes of a single pin are different from ti814x
	 * on some platforms, for such pins there will be more than one entry
	 * added, one for each platform, modes that are same as on ti814x
	 * are not repeated in the duplicate entry of the same pin/signal to
	 * avoid duplication of muxmodes. Modes that are new/replacement of old
	 * ones are added to the later entries of the pin
	 */
	_TI814X_MUXENTRY(MMC1_CLK, 0,
			"mmc1_clk", NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC1_CLK, 0,
			"mmc1_clk_ti811x", NULL, "pr1_mii_mt1_clk_mux0", NULL,
			NULL, NULL, NULL, "gpio4_11", NULL, NULL, NULL,
			NULL), /* for TI811X only*/
	_TI814X_MUXENTRY(MMC1_CMD, 0,
			"mmc1_cmd_mux0", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio0_0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC1_CMD, 0,
			"mmc1_cmd_mux0_ti811x", NULL, "pr1_mii1_txd3_mux0",
			NULL, NULL, "ehrpwm1_tripzone_input_mux0", NULL, NULL,
			NULL, NULL, NULL, NULL), /*for TI811X only*/
	_TI814X_MUXENTRY(MMC1_DAT0, 0,
			"mmc1_dat0", NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC1_DAT0, 0,
			"mmc1_dat0_ti811x", NULL, "pr1_mii1_txd2_mux0", NULL,
			NULL, NULL, NULL, "gpio4_12", NULL, NULL, NULL,
			NULL), /* for TI811X only */
	_TI814X_MUXENTRY(MMC1_DAT1, 0,
			"mmc1_dat1", NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC1_DAT1, 0,
			"mmc1_dat1_ti811x", NULL, "pr1_mii1_txd1_mux0", NULL,
			NULL, "ehrpwm1A_mux0", NULL, "gpio4_13",
			NULL, NULL, NULL, NULL), /* for TI811X only */
	_TI814X_MUXENTRY(MMC1_DAT2, 0,
			"mmc1_dat2", NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC1_DAT2, 0,
			"mmc1_dat2_ti811x", NULL, "pr1_mii1_txd0_mux0", NULL,
			NULL, "ehrpwm1B_mux0", NULL, "gpio4_14",
			NULL, NULL, NULL, NULL), /* for TI811X only */
	_TI814X_MUXENTRY(MMC1_DAT3, 0,
			"mmc1_dat3", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC1_DAT3, 0,
			"mmc1_dat3_ti811x", NULL, "pr1_mii1_crs_mux0",
			"pr1_pru0_pru_r30_16_mux1", "pr1_pru0_pru_r31_16_mux1",
			"eQEP2_index_mux0", NULL, "gpio4_15",
			NULL, NULL, NULL, NULL), /* for TI811X only */
	_TI814X_MUXENTRY(OSC_WAKE, 0,
			"osc_wake", "spi1_cs1", NULL, NULL, NULL, NULL,
			"timer5_mux1", "gpio1_07_mux0",	NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(OSC_WAKE, 0,
			"osc_wake_ti811x", NULL, "pr1_mii1_crs_mux2",
			"pr1_pru0_pru_r30_16_mux0", "pr1_pru0_pru_r31_16_mux0",
			NULL, NULL, NULL, NULL, NULL, NULL,
			NULL), /* for TI811X only */

	/* sc1_xxx mux options below are not on DM385 */
	_TI814X_MUXENTRY(MMC0_CLK, 0,
			"mmc0_clk", NULL, NULL, "sc1_c4", NULL, NULL, NULL,
			"gpio0_1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC0_CLK, 0,
			"mmc0_clk_ti811x", NULL, NULL, NULL, NULL,
			"ehrpwm2A_mux0", NULL, NULL, NULL, NULL, NULL,
			NULL),/* TI811X only */
	_TI814X_MUXENTRY(MMC0_CMD, 0,
			"mmc0_cmd", "mmc1_cmd_mux1", NULL, "sc1_det", NULL,
			NULL, NULL, "gpio0_2", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC0_CMD, 0,
			"mmc0_cmd_ti811x", NULL, NULL, NULL, NULL,
			"ehrpwm2B_mux0", NULL, NULL, NULL, NULL, NULL,
			NULL), /* for TI811X only */
	_TI814X_MUXENTRY(MMC0_DAT0, 0,
			"mmc0_dat0", "mmc1_dat4", NULL, "sc1_data", NULL, NULL,
			NULL, "gpio0_3", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC0_DAT0, 0,
			"mmc0_dat0_ti811x", NULL, NULL, NULL, NULL,
			"ehrpwm2_tripzone_input_mux0", NULL, NULL, NULL, NULL,
			NULL, NULL), /* for TI811X only */
	_TI814X_MUXENTRY(MMC0_DAT1, 0,
			"mmc0_dat1", "mmc1_dat5", NULL, "sc1_clk",
			NULL, NULL, NULL, "gpio0_4", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC0_DAT2, 0,
			"mmc0_dat2", "mmc1_dat6", NULL, "sc1_rst", NULL, NULL,
			NULL, "gpio0_5", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC0_DAT3, 0,
			"mmc0_dat3", "mmc1_dat7", NULL, "sc1_vccen",
			NULL, NULL, NULL, "gpio0_6", NULL, NULL, NULL, NULL),

	/* mcasp3/4/5_xxx mux options below are not on DM385 */
	_TI814X_MUXENTRY(XREF_CLK0, 0,
			"xref_clk0", "mcasp0_axr_7_mux1", "mcasp0_ahclkx",
			"mcasp3_ahclkx", "atlclkout1", "atlclkout0", "vic0",
			"usb1_drvvbus", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(XREF_CLK0, 0,
			"xref_clk0", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, "pr1_pru0_pru_r31_16_mux2", NULL, NULL, NULL),
	_TI814X_MUXENTRY(XREF_CLK1, 0,
			"xref_clk1", "mcasp0_axr_8_mux1", "mcasp1_ahclkx",
			"mcasp4_ahclkx", "atlclkout2", "xdma_evt_3_mux1",
			"timer2_mux1", "gpio0_8", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(XREF_CLK2, 0,
			"xref_clk2", "mcasp0_axr_9_mux1", "mcasp2_ahclkx",
			"mcasp5_ahclkx", "atlclkout3", "xdma_evt_2_mux1",
			"timer3_mux1", "gpio0_9", NULL, NULL, NULL,
			NULL),/* Not for DM385 */
	_TI814X_MUXENTRY(XREF_CLK2, 0,
			"xref_clk2_ti813x", NULL, NULL,	"sata_act1_led_mux0",
			NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL), /* DM385 only */
	_TI814X_MUXENTRY(MCASP0_ACLKX, 0,
			"mcasp0_aclkx", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP0_ACLKX, 0,
			"mcasp0_aclkx_ti811x", NULL, "pr1_mii1_rxd3_mux0",
			"pr1_pru0_pru_r31_0", "pr1_pru0_pru_r30_0", NULL,
			"eQEP1A_in_mux0", NULL,	NULL, NULL, NULL,
			NULL), /* for TI811X only */
	_TI814X_MUXENTRY(MCASP0_FSX, 0,
			"mcasp0_fsx", NULL, NULL, NULL,	NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP0_FSX, 0,
			"mcasp0_fsx_ti811x", NULL, "pr1_mii1_rxd2_mux0",
			"pr1_pru0_pru_r31_1", "pr1_pru0_pru_r30_1", NULL,
			"eQEP1B_in_mux0", NULL,	NULL, NULL, NULL,
			NULL), /* for TI811X only */
	_TI814X_MUXENTRY(MCASP0_CLKR, 0,
			"mcasp0_aclkr", "mcasp5_axr2", NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP0_CLKR, 0,
			"mcasp0_aclkr_ti811x", NULL, "pr1_mii1_rxd1_mux0",
			"pr1_pru0_pru_r31_2", "pr1_pru0_pru_r30_2", NULL,
			"eQEP1_index_mux0", NULL, NULL, NULL, NULL,
			NULL), /* for TI811X only*/
	_TI814X_MUXENTRY(MCASP0_FSR, 0,
			"mcasp0_fsr", "mcasp5_axr3", NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP0_FSR, 0,
			"mcasp0_fsr_ti811x", NULL, "pr1_mii1_rxd0_mux0",
			"pr1_pru0_pru_r31_3", "pr1_pru0_pru_r30_3", NULL,
			"eQEP1_strobe_mux0", NULL, NULL, NULL, NULL,
			NULL), /* for TI811X only */
	_TI814X_MUXENTRY(MCASP0_AXR0, 0,
			"mcasp0_axr0", NULL, NULL, NULL, NULL, "vic1", NULL,
			NULL, NULL, NULL, NULL, NULL),	/* vic1 not for DM385 */
	_TI814X_MUXENTRY(MCASP0_AXR0, 0,
			"mcasp0_axr0_ti811x", NULL, "pr1_mii_mr1_clk_mux0",
			"pr1_pru0_pru_r31_4", "pr1_pru0_pru_r30_4", "vic1",
			"ehrpwm1A_mux1", NULL, NULL, NULL, NULL,
			NULL), /* for TI811X only */
	_TI814X_MUXENTRY(MCASP0_AXR1, 0,
			"mcasp0_axr1", NULL, NULL, NULL, NULL, "i2c3_scl_mux0",
			NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP0_AXR1, 0,
			"mcasp0_axr1_ti811x", NULL, "pr1_mii_mt0_clk_mux0",
			"pr1_pru0_pru_r31_5", "pr1_pru0_pru_r30_5",
			"i2c3_scl_mux0", "ehrpwm1B_mux1", NULL,
			"mmc1_sdwp_mux1", NULL, NULL, NULL),/* for TI811X only*/
	_TI814X_MUXENTRY(MCASP0_AXR2, 0,
			"mcasp0_axr2", NULL, NULL, NULL, NULL, "i2c3_sda_mux0",
			NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP0_AXR2, 0,
			"mcasp0_axr2_ti811x", NULL, "pr1_mii0_rxlink_mux0",
			"pr1_pru0_pru_r31_6", "pr1_pru0_pru_r30_6",
			"i2c3_sda_mux0", "ehrpwm1_tripzone_input_mux1", NULL,
			"mmc1_sdcd_mux1", NULL, NULL, NULL),/*for TI811X only */
	_TI814X_MUXENTRY(MCASP0_AXR3, 0,
			"mcasp0_axr3", NULL, NULL, "sc1_vppen",	NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL),/*sci not on DM385*/
	_TI814X_MUXENTRY(MCASP0_AXR3, 0,
			"mcasp0_axr3_ti811x", NULL, "pr1_mii1_col_mux0", NULL,
			"pr1_pru0_pru_r30_7", "pr1_pru0_pru_r31_7", NULL, NULL,
			NULL, NULL, NULL, NULL), /* for TI811X only */
	_TI814X_MUXENTRY(MCASP0_AXR4, 0,
			"mcasp0_axr4", "mcasp1_axr_8_mux0", NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP0_AXR4, 0,
			"mcasp0_axr4_ti811x", NULL, "pr1_mii0_col_mux0",
			"pr1_pru0_pru_r31_8", "pr1_pru0_pru_r30_8", NULL,
			"eQEP2A_in_mux0", NULL,	NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP0_AXR5, 0,
			"mcasp0_axr5", "mcasp1_axr_9_mux0", NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP0_AXR5, 0,
			"mcasp0_axr5_ti811x", NULL, "pr1_mii0_rxer_mux0",
			"pr1_pru0_pru_r31_9", "pr1_pru0_pru_r30_9", NULL,
			"eQEP2B_in_mux0", NULL,	NULL, NULL, NULL,
			NULL),/*for TI811X only */

	/* Following 4 groups not on DM385 */
	_TI814X_MUXENTRY(MCASP0_AXR6, 0,
			"mcasp0_axr6", "mcbsp_dr", NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP0_AXR6, 0,
			"mcasp0_axr6_ti811x", NULL, NULL, "pr1_pru0_pru_r31_10",
			"pr1_pru0_pru_r30_10", NULL, NULL, NULL, NULL, NULL,
			NULL, NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP0_AXR7, 0,
			"mcasp0_axr_7_mux0", "mcbsp_dx", NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP0_AXR7, 0,
			"mcasp0_axr_7_mux0_ti811x", NULL, NULL,
			"pr1_pru0_pru_r31_11", "pr1_pru0_pru_r30_11", NULL,
			NULL, NULL, NULL, NULL, NULL, NULL),/*for TI811X only */
	_TI814X_MUXENTRY(MCASP0_AXR8, 0,
			"mcasp0_axr_8_mux0", "mcbsp_fsx", "mcbsp_fsr_mux1",
			NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP0_AXR8, 0,
			"mcasp0_axr_8_mux0_ti811x", NULL, NULL,
			"pr1_pru0_pru_r31_12", "pr1_pru0_pru_r30_12", NULL,
			NULL, NULL, "mmc0_sdwp", NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP0_AXR9, 0,
			"mcasp0_axr_9_mux0", "mcbsp_clkx", "mcbsp_clkr_mux1",
			NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP0_AXR9, 0,
			"mcasp0_axr_9_mux0_ti811x", NULL, NULL,	NULL, NULL,
			NULL, NULL, NULL, "mmc0_sdcd_mux1", NULL, NULL,
			NULL),/* for TI811X only */

	_TI814X_MUXENTRY(MCASP1_ACLKX, 0,
			"mcasp1_aclkx", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP1_ACLKX, 0,
			"mcasp1_aclkx_ti811x", NULL, "pr1_mii0_txen_mux0", NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP1_FSX, 0,
			"mcasp1_fsx", NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP1_FSX, 0,
			"mcasp1_fsx_ti811x", NULL, "pr1_mii0_txd3_mux0", NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP1_CLKR, 0,
			"mcasp1_aclkr", "mcasp1_axr4", NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP1_CLKR, 0,
			"mcasp1_aclkr_ti811x", NULL, "pr1_mii0_txd2_mux0", NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP1_FSR, 0,
			"mcasp1_fsr", "mcasp1_axr5", NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP1_FSR, 0,
			"mcasp1_fsr_ti811x", NULL, "pr1_mii1_rxer_mux0", NULL,
			NULL, NULL, "ehrpwm0A_mux0", NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */

	/* sc0_xxx not on DM385 */
	_TI814X_MUXENTRY(MCASP1_AXR0, 0,
			"mcasp1_axr0", "mmc0_dat4", NULL, "sc0_rst", NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP1_AXR0, 0,
			"mcasp1_axr0_ti811x", NULL, "pr1_mii1_rxdv_mux0", NULL,
			NULL, NULL, "ehrpwm0B_mux0", NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP1_AXR1, 0,
			"mcasp1_axr1", "mmc0_dat5", NULL, "sc0_det", NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP1_AXR1, 0,
			"mcasp1_axr1_ti811x", NULL, "pr1_mii1_txen_mux0", NULL,
			NULL, NULL, "ehrpwm0_tripzone_input_mux0", NULL, NULL,
			NULL, NULL, NULL),/* for TI811X only */

	/* Following 4 groups not on DM385 */
	_TI814X_MUXENTRY(MCASP1_AXR2, 0,
			"mcasp1_axr2", "mcbsp_fsr_mux0", NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP1_AXR2, 0,
			"mcasp1_axr2_ti811x", NULL, "eCAP2_in_PWM2_out_mux0",
			NULL, NULL, "ehrpwm0_synci_mux0", "ehrpwm0_synco_mux0",
			NULL, NULL, NULL, NULL, NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP1_AXR3, 0,
			"mcasp1_axr3", "mcbsp_clkr_mux0", NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP1_AXR3, 0,
			"mcasp1_axr3_ti811x", NULL, "pr1_mii1_rxlink_mux0",
			NULL, NULL, NULL, "eQEP0A_in", NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP2_CLKX, 0,
			"mcasp2_aclkx", NULL, NULL, "sc0_c4", NULL, NULL, NULL,
			"gpio0_10_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP2_CLKX, 0,
			"mcasp2_aclkx_ti811x", "pr1_mii0_txd1_mux0", NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP2_FSX, 0,
			"mcasp2_fsx", NULL, NULL, "sc0_data", NULL, NULL, NULL,
			"gpio0_11_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP2_FSX, 0,
			"mcasp2_fsx_ti811x", "pr1_mii0_txd0_mux0", NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */

	/*
	 * XXX: On DM385, mode0 does not exist, still we keep it to allow
	 * referring to intermediate mode(s).
	 *
	 * Also, following are removed for DM385:
	 *	sc0_xxx, uart5_xxx
	 */
	_TI814X_MUXENTRY(MCASP2_AXR0, 0,
			"mcasp2_axr0", "mmc0_dat6", NULL, "sc0_clk", NULL,
			"uart5_rxd_mux3", NULL, "gpio0_12_mux1", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(MCASP2_AXR0, 0,
			"mcasp2_axr0_ti811x", NULL, NULL, NULL, "eQEP0B_in",
			NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP2_AXR1, 0,
			"mcasp2_axr1", "mmc0_dat7", NULL, "sc0_vccen", NULL,
			"uart5_txd_mux3", NULL, "gpio0_13_mux1", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(MCASP2_AXR1, 0,
			"mcasp2_axr1_ti811x", NULL, NULL, NULL, "eQEP0_index",
			NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */

	/* Following group is removed for DM385 */
	_TI814X_MUXENTRY(MCASP2_AXR2, 0,
			"mcasp2_axr2", "mcasp1_axr6", NULL, "sc0_vppen", NULL,
			NULL, "timer2_mux0", "gpio0_14_mux1", NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(MCASP2_AXR2, 0,
			"mcasp2_axr2_ti811x", NULL, "pr1_mii_mr0_clk_mux0",
			NULL, "eQEP0_strobe", NULL, NULL, NULL, NULL, NULL,
			NULL, NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP2_AXR3, 0,
			"mcasp2_axr3", "mcasp1_axr7", NULL, "tso0_pacerr", NULL,
			NULL, "timer3_mux0", "gpio0_15_mux1", NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(MCASP2_AXR3, 0,
			"mcasp2_axr3_ti811x", NULL, "pr1_mii0_rxdv_mux0", NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP3_CLKX, 0,
			"mcasp3_aclkx", NULL, NULL, "tsi0_dclk", NULL, NULL,
			NULL, "gpio0_16_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP3_CLKX, 0,
			"mcasp3_aclkx_ti811x", NULL, NULL, NULL,
			"pr1_pru0_pru_r31_20", "pr1_pru0_pru_r30_20", NULL,
			NULL, NULL, NULL, NULL,	NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP3_FSX, 0,
			"mcasp3_fsx", NULL, NULL, "tsi0_bytstrt", NULL, NULL,
			NULL, "gpio0_17_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP3_FSX, 0,
			"mcasp3_fsx_ti811x", NULL, NULL, NULL,
			"pr1_pru0_pru_r31_19", "pr1_pru0_pru_r30_19", NULL,
			NULL, NULL, NULL, NULL, NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP3_AXR0, 0,
			"mcasp3_axr0", NULL, NULL, "tsi0_data",	NULL, NULL,
			"timer4_mux0", "gpio0_18_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP3_AXR0, 0,
			"mcasp3_axr0_ti811x", NULL, NULL, NULL,
			"pr1_pru0_pru_r31_18", "pr1_pru0_pru_r30_18", NULL,
			NULL, NULL, NULL, NULL, NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP3_AXR1, 0,
			"mcasp3_axr1", NULL, NULL, "tsi0_pacval", NULL, NULL,
			"timer5_mux0", "gpio0_19_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP3_AXR1, 0,
			"mcasp3_axr1_ti811x", NULL, NULL, NULL,
			"pr1_pru0_pru_r31_17", "pr1_pru0_pru_r30_17", NULL,
			NULL, NULL, NULL, NULL,	NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP3_AXR2, 0,
			"mcasp3_axr2", "mcasp1_axr_8_mux1", NULL, "tsi0_pacerr",
			NULL, NULL, NULL, "gpio0_20_mux1", NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(MCASP3_AXR2, 0,
			"mcasp3_axr2_ti811x", NULL, "pr1_mii0_rxd3_mux0", NULL,
			"eQEP2_index_mux2", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP3_AXR3, 0,
			"mcasp3_axr3", "mcasp1_axr_9_mux1", NULL, "tsi2_pacerr",
			NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP3_AXR3, 0,
			"mcasp3_axr3_ti811x", NULL, "pr1_mii0_rxd2_mux0", NULL,
			"eQEP2_strobe_mux0", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP4_CLKX, 0,
			"mcasp4_aclkx", NULL, NULL, "tsi2_dclk", NULL, NULL,
			NULL, "gpio0_21_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP4_CLKX, 0,
			"mcasp4_aclkx_ti811x", NULL, NULL, NULL,
			"pr1_pru0_pru_r31_14", "pr1_pru0_pru_r30_14", NULL,
			NULL, NULL, NULL, NULL, NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP4_FSX, 0,
			"mcasp4_fsx", NULL, NULL, "tsi2_bytstrt", NULL, NULL,
			NULL, "gpio0_22_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP4_FSX, 0,
			"mcasp4_fsx_ti811x", "pr1_mii0_rxd1_mux0", NULL, NULL,
			"pr1_pru0_pru_r31_15", "pr1_pru0_pru_r30_15", NULL,
			NULL, NULL, NULL, NULL,	NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP4_AXR0, 0,
			"mcasp4_axr0", NULL, NULL, "tsi2_data", NULL, NULL,
			NULL, "gpio0_23_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP4_AXR0, 0,
			"mcasp4_axr0_ti811x", "pr1_mii0_rxd0_mux0", NULL, NULL,
			"pr1_pru0_pru_r31_13", "pr1_pru0_pru_r30_13", NULL,
			NULL, NULL, NULL, NULL, NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP4_AXR1, 0,
			"mcasp4_axr1", NULL, NULL, "tsi2_pacval", NULL, NULL,
			"timer6_mux0", "gpio0_24_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP4_AXR1, 0,
			"mcasp4_axr1_ti811x", "pr1_mii0_crs_mux0", NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP5_CLKX, 0,
			"mcasp5_aclkx", NULL, NULL, "tso0_dclk", NULL, NULL,
			NULL, "gpio0_25_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP5_FSX, 0,
			"mcasp5_fsx", NULL, NULL, "tso0_bytstrt", NULL, NULL,
			NULL, "gpio0_26_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP5_AXR0, 0,
			"mcasp5_axr0", "mcasp4_axr2", NULL, "tso0_data", NULL,
			NULL, NULL, "gpio0_27_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MCASP5_AXR0, 0,
			"mcasp5_axr0_ti811x", NULL, NULL, NULL,	NULL,
			"pr1_ecap0_ecap_capin_apwm_o_mux0", NULL, NULL,	NULL,
			NULL, NULL, NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MCASP5_AXR1, 0,
			"mcasp5_axr1", "mcasp4_axr3", NULL, "tso0_pacval",
			NULL, NULL, "timer7_mux0", "gpio0_28_mux1", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(MCASP5_AXR1, 0,
			"mcasp5_axr1_ti811x", NULL, NULL, NULL,	NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL),/*for TI811X only */
	_TI814X_MUXENTRY(MLB_SIG, 0,
			"mlb_sig", NULL, NULL, "uart2_rxd_mux1", NULL, NULL,
			NULL, "gpio0_29", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MLB_DAT, 0,
			"mlb_dat", NULL, NULL, "tclkin", NULL, NULL, NULL,
			"gpio0_30", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MLB_CLK, 0,
			"mlb_clk", NULL, NULL, "uart2_txd_mux1", NULL, NULL,
			NULL, "gpio0_31", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MLBP_SIG_P, 0,
			"mlbp_sig_p", NULL, NULL, NULL,	NULL, NULL, NULL,
			"gpio1_07_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MLBP_SIG_N, 0,
			NULL, NULL, NULL, NULL,	NULL, NULL, NULL,
			"gpio1_08_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MLBP_DAT_P, 0,
			"mlbp_dat_p", NULL, NULL, NULL,	NULL, NULL, NULL,
			"gpio1_09_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MLBP_DAT_N, 0,
			NULL, NULL, NULL, NULL,	NULL, NULL, NULL,
			"gpio1_10_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MLBP_CLK_P, 0,
			"mlbp_clk_p", NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MLBP_CLK_N, 0,
			"mlbp_clk_n", NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),

	_TI814X_MUXENTRY(DCAN0_TX, 0,
			"dcan0_tx", "uart2_txd_mux2", NULL, NULL, NULL,
			"i2c3_sda_mux1", NULL, "gpio1_0", NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(DCAN0_RX, 0,
			"dcan0_rx", "uart2_rxd_mux2", NULL, NULL, NULL,
			"i2c3_scl_mux1", NULL, "gpio1_1", NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(UART0_RXD, 0,
			"uart0_rxd", NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(UART0_TXD, 0,
			"uart0_txd", NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),

	/* uart3/uart4_xxx not there for DM385 */
	_TI814X_MUXENTRY(UART0_CTSN, 0,
			"uart0_ctsn", "uart4_rxd_mux3", NULL, "dcan1_tx",
			"spi1_cs3", NULL, "mmc0_sdcd", NULL, NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(UART0_CTSN, 0,
			"uart0_ctsn_ti811x", NULL, NULL, NULL,
			"spi1_cs3", NULL, NULL, "gpio4_16", NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(UART0_RTSN, 0,
			"uart0_rtsn", "uart4_txd_mux3", NULL, "dcan1_rx",
			"spi1_cs2", NULL, "mmc2_sdcd", NULL, NULL, NULL, NULL,
			NULL),	/* non DM385 */
	_TI814X_MUXENTRY(UART0_RTSN, 0,
			"uart0_rtsn_ti813x", "sata_act1_led_mux", NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* DM385 only */
	_TI814X_MUXENTRY(UART0_RTSN, 0,
			"uart0_rtsn_ti811x", NULL, NULL, NULL,
			NULL, NULL, NULL, "gpio4_17", NULL, NULL, NULL,
			NULL),/* for TI811X only */

	/* "mmc1_pow_mux0" on TI811X is "mmc1_pow" below */
	_TI814X_MUXENTRY(UART0_DCDN, 0,
			"uart0_dcdn", "uart3_rxd_mux0", NULL, NULL, "spi0_cs3",
			"i2c2_scl_mux0", "mmc1_pow", "gpio1_2", NULL, NULL,
			NULL, NULL),

	/* "mmc1_sdwp_mux0" on TI811X is "mmc1_sdwp" below */
	_TI814X_MUXENTRY(UART0_DSRN, 35,
			"uart0_dsrn", "uart3_txd_mux0", NULL, NULL, "spi0_cs2",
			"i2c2_sda_mux0", "mmc1_sdwp", "gpio1_3", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(UART0_DTRN, 0,
			"uart0_dtrn", "uart3_ctsn_mux0", "uart1_txd_mux0", NULL,
			NULL, NULL, NULL, "gpio1_4", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(UART0_DTRN, 0,
			"uart0_dtrn_ti811x", NULL, NULL, "pr1_pru1_pru_r30_14",
			"pr1_pru1_pru_r31_14", "eCAP2_in_PWM2_out_mux1", NULL,
			NULL, NULL, NULL, NULL, NULL),/* for TI811X only */
	_TI814X_MUXENTRY(UART0_RIN, 0,
			"uart0_rin", "uart3_rtsn_mux0", "uart1_rxd_mux0", NULL,
			NULL, NULL, NULL, "gpio1_5", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(UART0_RIN, 0,
			"uart0_rin_ti811x", NULL, NULL, "pr1_pru1_pru_r30_15",
			"pr1_pru1_pru_r31_15", "eCAP1_in_PWM1_out_mux0", NULL,
			NULL, NULL, NULL, NULL, NULL),/* for TI811X only */

	_TI814X_MUXENTRY(I2C1_SCL, 0,
			"i2c1_scl", "hdmi_ddc_scl_mux0", NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(I2C1_SDA, 0,
			"i2c1_sda", "hdmi_ddc_sda_mux0", NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(SPI0_CS1, 38,
			"spi0_cs1", "mmc1_sdcd", "sata_act0_led", NULL, NULL,
			"xdma_evt_1_mux1", "timer4_mux1", "gpio1_6", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(SPI0_CS1, 0,
			"spi0_cs1_ti811x", "mmc1_sdcd_mux0", NULL,
			"ehrpwm0A_mux1", "pr1_ecap0_ecap_capin_apwm_o_mux1",
			NULL, NULL, NULL, "eCAP0_in_PWM0_out", NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(SPI0_CS0, 0,
			"spi0_cs0", NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(SPI0_CS0, 0,
			"spi0_cs0_ti811x", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio4_18", NULL, NULL, NULL, NULL),/*for TI811X only */
	_TI814X_MUXENTRY(SPI0_SCLK, 0,
			"spi0_sclk", NULL, NULL, NULL, NULL, NULL, "`",
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(SPI0_SCLK, 0,
			"spi0_sclk_ti811x", NULL, NULL,
			"ehrpwm0_tripzone_input_mux1", NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),/* for TI811X only */
	_TI814X_MUXENTRY(SPI0_D1, 0,
			"spi0_d1", NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(SPI0_D1, 0,
			"spi0_d1_ti811x", NULL, "ehrpwm0_synci_mux1",
			"ehrpwm0_synco_mux1", NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL),/* for TI811X only */
	_TI814X_MUXENTRY(SPI0_D0, 0,
			"spi0_d0", NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(SPI0_D0, 0,
			"spi0_d0_ti811x", NULL, NULL, "ehrpwm0B_mux1", NULL,
			NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(SPI1_CS0, 0,
			"spi1_cs0", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio1_16_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(SPI1_SCLK, 0,
			"spi1_sclk", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio1_17_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(SPI1_D1, 0,
			"spi1_d1", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio1_18_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(SPI1_D1, 0,
			"spi1_d1_ti811x", NULL, NULL, "eCAP2_in_PWM2_out_mux2",
			NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(SPI1_D0, 0,
			"spi1_d0", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio1_26_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(SPI1_D0, 0,
			"spi1_d0_ti811x", NULL, NULL, "eCAP1_in_PWM1_out_mux1",
			NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(GPMC_AD00, 0,
			"gpmc_ad0", NULL, NULL, NULL, NULL, NULL, NULL,
			"boot0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD01, 0,
			"gpmc_ad1", NULL, NULL, NULL, NULL, NULL, NULL,
			"boot1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD02, 0,
			"gpmc_ad2", NULL, NULL, NULL, NULL, NULL, NULL,
			"boot2", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD03, 0,
			"gpmc_ad3", NULL, NULL, NULL, NULL, NULL, NULL,
			"boot3", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD04, 0,
			"gpmc_ad4", NULL, NULL, NULL, NULL, NULL, NULL,
			"boot4", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD05, 0,
			"gpmc_ad5", NULL, NULL, NULL, NULL, NULL, NULL,
			"boot5", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD06, 0,
			"gpmc_ad6", NULL, NULL, NULL, NULL, NULL, NULL,
			"boot6", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD07, 0,
			"gpmc_ad7", NULL, NULL, NULL, NULL, NULL, NULL,
			"boot7", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD08, 0,
			"gpmc_ad8", NULL, NULL, NULL, NULL, NULL, NULL,
			"boot8", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD09, 0,
			"gpmc_ad9", NULL, NULL, NULL, NULL, NULL, NULL,
			"boot9", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD10, 0,
			"gpmc_ad10", NULL, NULL, NULL, NULL, NULL, NULL,
			"boot10", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD11, 0,
			"gpmc_ad11", NULL, NULL, NULL, NULL, NULL, NULL,
			"boot11", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD12, 0,
			"gpmc_ad12", NULL, NULL, NULL, NULL, NULL, NULL,
			"boot12", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD13, 0,
			"gpmc_ad13", NULL, NULL, NULL, NULL, NULL, NULL,
			"boot13", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD14, 0,
			"gpmc_ad14", NULL, NULL, NULL, NULL, NULL, NULL,
			"boot14", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD15, 0,
			"gpmc_ad15", NULL, NULL, NULL, NULL, NULL, NULL,
			"boot15", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_A16, 0,
			"gpmc_a16", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio2_05_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_A17, 0,
			"gpmc_a17", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio2_06_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_A18, 0,
			"gpmc_a18", NULL, NULL, NULL, NULL, NULL, "timer2_mux2",
			"gpio1_13_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_A19, 0,
			"gpmc_a19", NULL, NULL, NULL, NULL, NULL, "timer3_mux2",
			"gpio1_14_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_A20, 0,
			"gpmc_a_20_mux0", NULL, "spi2_cs1", NULL, NULL, NULL,
			NULL, "gpio1_15_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_A21, 0,
			"gpmc_a_21_mux0", NULL, "spi2_d_0_mux0", NULL, NULL,
			NULL, NULL, "gpio1_16_mux0", NULL, NULL, NULL, NULL),

	/* following gpmc_ad0_ti811x to gpmc_ad21_ti811x are only on TI811X */

	_TI814X_MUXENTRY(GPMC_AD00, 0,
			"gpmc_ad0_ti811x", NULL, "spi2_d_1_mux3", NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD01, 0,
			"gpmc_ad1_ti811x", NULL, "spi2_d_0_mux3", NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD04, 0,
			"gpmc_ad4_ti811x", NULL, NULL, NULL, NULL, NULL,
			"gpio5_6", NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD05, 0,
			"gpmc_ad5_ti811x", NULL, NULL, NULL, NULL, NULL,
			"gpio5_7", NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD06, 0,
			"gpmc_ad6_ti811x", NULL, NULL, NULL,
			"ehrpwm2_tripzone_input_mux2", NULL, "gpio5_8", NULL,
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD07, 0,
			"gpmc_ad7_ti811x", NULL, NULL, NULL, NULL, NULL,
			"gpio5_9", NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD08, 0,
			"gpmc_ad8_ti811x", NULL, NULL, "uart7_txd_mux2", NULL,
			NULL, "gpio4_0", NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD09, 0,
			"gpmc_ad9_ti811x", NULL, NULL, "uart7_rxd_mux2", NULL,
			NULL, "gpio4_1", NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD10, 0,
			"gpmc_ad10_ti811x", NULL, NULL, "uart7_rtsn_mux2", NULL,
			NULL, "gpio4_2", NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD11, 0,
			"gpmc_ad11_ti811x", NULL, NULL, "uart7_ctsn_mux2", NULL,
			NULL, "gpio4_3", NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD12, 0,
			"gpmc_ad12_ti811x", NULL, NULL, NULL, "ehrpwm2A_mux2",
			NULL, "gpio4_4", NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD13, 0,
			"gpmc_ad13_ti811x", NULL, NULL, NULL, "ehrpwm2B_mux2",
			NULL, "gpio4_5", NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD14, 0,
			"gpmc_ad14_ti811x", NULL, NULL, NULL, NULL, NULL,
			"gpio4_6", NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_AD15, 0,
			"gpmc_ad15_ti811x", NULL, NULL, NULL, NULL, NULL,
			"gpio4_7", NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_A16, 0,
			"gpmc_a16_ti811x", NULL, NULL, "i2c2_scl_mux4", NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_A17, 0,
			"gpmc_a17_ti811x", NULL, NULL, "i2c2_sda_mux4", NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_A18, 0,
			"gpmc_a18_ti811x", NULL, NULL, "i2c3_scl_mux4", NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_A19, 0,
			"gpmc_a19_ti811x", NULL, NULL, "i2c3_sda_mux4", NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_A20, 0,
			"gpmc_a_20_mux0_ti811x", "gpmc_a_26_invert", NULL, NULL,
			NULL, NULL, "gpio4_8", NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_A21, 0,
			"gpmc_a_21_mux0_ti811x", "gpmc_a_27_invert", NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

	_TI814X_MUXENTRY(GPMC_A22, 0,
			"gpmc_a_22_mux0", NULL, "spi2_d_1_mux0", NULL,
			"hdmi_cec_mux0", NULL, "timer4_mux2", "gpio1_17_mux0",
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_A23, 0,
			"gpmc_a_23_mux0", NULL, "spi2_sclk_mux0", NULL,
			"hdmi_hpd_mux0", NULL, "timer5_mux2", "gpio1_18_mux0",
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC2_DAT7, 0,
			"mmc2_dat7", "gpmc_a_24_mux0", "gpmc_a_20_mux1", NULL,
			NULL, "uart2_rxd_mux3", NULL, "gpio1_19", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(MMC2_DAT7, 0,
			"mmc2_dat7_ti811x", NULL, NULL, NULL, "vin1_hsync1",
			NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MMC2_DAT6, 0,
			"mmc2_dat6", "gpmc_a_25_mux0", "gpmc_a_21_mux1", NULL,
			NULL, "uart2_txd_mux3", NULL, "gpio1_20", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(MMC2_DAT6, 0,
			"mmc2_dat6_ti811x", NULL, NULL, NULL, "vin1_vsync1",
			NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(MMC2_DAT5, 0,
			"mmc2_dat5", "gpmc_a_26_mux0", "gpmc_a_22_mux1", NULL,
			NULL, NULL, "timer6_mux2", "gpio1_21", NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(MMC2_DAT4, 0,
			"mmc2_dat4", "gpmc_a_27_mux0", "gpmc_a_23_mux1",
			"gpmc_cs7", NULL, "xdma_evt_0_mux1", "timer7_mux2",
			"gpio1_22", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC2_DAT3, 0,
			"mmc2_dat3", "gpmc_a_1_mux1", NULL, NULL, NULL, NULL,
			NULL, "gpio2_05_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC2_DAT2, 0,
			"mmc2_dat2", "gpmc_a_2_mux1", NULL, NULL, NULL, NULL,
			NULL, "gpio2_06_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC2_DAT1, 0,
			"mmc2_dat1", "gpmc_a_3_mux1", NULL, NULL, NULL, NULL,
			NULL, "gpio1_13_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC2_DAT0, 0,
			"mmc2_dat0", "gpmc_a_4_mux1", NULL, NULL, NULL, NULL,
			NULL, "gpio1_14_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MMC2_CLK, 0,
			"mmc2_clk", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio1_15_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_CS0, 0,
			"gpmc_cs0", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio1_23", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_CS1, 0,
			"gpmc_cs1", "gpmc_a_25_mux1", NULL, NULL, NULL, NULL,
			NULL, "gpio1_24", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_CS2, 0,
			"gpmc_cs2", "gpmc_a_24_mux1", NULL, NULL, NULL, NULL,
			NULL, "gpio1_25", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_CS3, 0,
			"gpmc_cs3", "vin1_clk1", "spi2_cs0", NULL, NULL, NULL,
			NULL, "gpio1_26_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_CS4, 0,
			"gpmc_cs4", "mmc2_cmd", NULL, NULL, NULL, NULL, NULL,
			"gpio1_08_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_CLK, 0,
			"gpmc_clk", "gpmc_cs5", NULL, "gpmc_wait1", "clkout1",
			"xdma_evt_3_mux0", "timer4_mux3", "gpio1_27", NULL,
			NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_CLK, 0,
			"gpmc_clk_ti811x", NULL, "spi2_sclk_mux3", NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(GPMC_ADVN_ALE, 0,
			"gpmc_advn_ale", "gpmc_cs6", NULL, NULL, NULL, NULL,
			"timer5_mux3", "gpio1_28", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_OEN_REN, 0,
			"gpmc_oen_ren", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_WEN, 0,
			"gpmc_wen", NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_BEN0, 0,
			"gpmc_ben0", "gpmc_a_25_mux2", NULL, NULL, NULL,
			"xdma_evt_2_mux0", "timer6_mux3", "gpio1_29", NULL,
			NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_BEN1, 0,
			"gpmc_ben1", "gpmc_a_24_mux2", NULL, NULL, NULL,
			"xdma_evt_1_mux0", "timer7_mux3", "gpio1_30", NULL,
			NULL, NULL, NULL),
	_TI814X_MUXENTRY(GPMC_WAIT0, 0,
			"gpmc_wait0", "gpmc_a_26_mux2", NULL, NULL, NULL,
			"xdma_evt_0_mux0", NULL, "gpio1_31", NULL, NULL, NULL,
			NULL),
	/* "clkout0_mux0" on TI811X is "cam_xclka" below */
	_TI814X_MUXENTRY(VIN0_CLK1, 0,
			"vin0_clk1", NULL, NULL, NULL, NULL, "cam_xclka", NULL,
			"gpio1_09_mux0", NULL, NULL, NULL, NULL),

	/* uart5 pins modes  are not for DM385 */
	_TI814X_MUXENTRY(VIN0_DE0_MUX0, 0,
			"vin0_de0_mux0", NULL, NULL, NULL, "vin0_hsync1",
			"uart5_txd_mux1", "i2c2_sda_mux1", "gpio2_0", NULL,
			NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_FLD0_MUX0, 0,
			"vin0_fld0_mux0", NULL, NULL, NULL, "vin0_vsync1",
			"uart5_rxd_mux1", "i2c2_scl_mux3", "gpio2_1", NULL,
			NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_CLK0, 0,
			"vin0_clk0", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio2_02_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_HSYNC0, 0,
			"vin0_hsync0", NULL, NULL, NULL, NULL,
			"uart5_rtsn_mux1", NULL, "gpio2_3", NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VIN0_VSYNC0, 0,
			"vin0_vsync0", NULL, NULL, NULL, NULL,
			"uart5_ctsn_mux1", NULL, "gpio2_4", NULL, NULL, NULL,
			NULL),

	_TI814X_MUXENTRY(VIN0_D0, 0,
			"vin0_d0", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio1_11_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D1, 0,
			"vin0_d1", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio1_12_mux1", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D2, 0,
			"vin0_d2", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio2_7", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D3, 0,
			"vin0_d3", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio2_8", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D4, 0,
			"vin0_d4", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio2_9", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D5, 0,
			"vin0_d5", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio2_10", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D6, 0,
			"vin0_d6", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio2_11", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D7, 0,
			"vin0_d7", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio2_12", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D8, 0,
			"vin0_d8", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio2_13", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D9, 0,
			"vin0_d9", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio2_14", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D10, 0,
			"vin0_d10", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio2_15", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D11, 0,
			"vin0_d11", NULL, NULL, NULL, NULL, "cam_de_mux1", NULL,
			"gpio2_16", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D12, 0,
			"vin0_d12", NULL, NULL, NULL, NULL, "cam_xclkb", NULL,
			"gpio2_17", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D13, 0,
			"vin0_d13", NULL, NULL, NULL, NULL, "cam_reset", NULL,
			"gpio2_18", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D14, 0,
			"vin0_d14", NULL, NULL, NULL, NULL, "cam_strobe", NULL,
			"gpio2_19", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D15, 0,
			"vin0_d15", NULL, NULL, NULL, NULL, "cam_shutter", NULL,
			"gpio2_20", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D16, 0,
			"vin0_d16", "cam_d8", NULL, NULL, NULL, "i2c2_scl_mux1",
			NULL, "gpio0_10_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D17, 0,
			"vin0_d17", "cam_d9", NULL, "rmii1_rxer_mux1", NULL,
			NULL, NULL, "gpio0_11_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D18, 0,
			"vin0_d18", "cam_d10", NULL, "rmii1_rxd1_mux1", NULL,
			"i2c3_scl_mux2", NULL, "gpio0_12_mux0", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D19, 0,
			"vin0_d19", "cam_d11", NULL, "rmii1_rxd0_mux1", NULL,
			"i2c3_sda_mux2", NULL, "gpio0_13_mux0", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D20, 0,
			"vin0_d20", "cam_d12", NULL, "rmii1_crs_mux1", NULL,
			"spi3_cs0", NULL, "gpio0_14_mux0", NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VIN0_D21, 0,
			"vin0_d21", "cam_d13", NULL, "rmii1_txd0_mux1", NULL,
			"spi3_sclk_mux0", NULL, "gpio0_15_mux0", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D22, 0,
			"vin0_d22", "cam_d14", NULL, "rmii1_txd1_mux1", NULL,
			"spi3_d_1_mux0", NULL, "gpio0_16_mux0", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D23, 0,
			"vin0_d23", "cam_d15", NULL, "rmii1_txen_mux1", NULL,
			"spi3_d_0_mux0", NULL, "gpio0_17_mux0", NULL, NULL,
			NULL, NULL),

	/* Following from VIN0_D0 to VIN0_D23 are on TI811X only */
	_TI814X_MUXENTRY(VIN0_D0, 0,
			"vin0_d0_ti811x", NULL, "pr1_edc_latch0_in_mux1", NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D1, 0,
			"vin0_d1_ti811x", NULL, "pr1_edc_latch1_in_mux1", NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D3, 0,
			"vin0_d3_ti811x", NULL, "pr1_edc_sync0_out_mux1", NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D4, 0,
			"vin0_d4_ti811x", NULL, "pr1_edc_sync1_out_mux1", NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D5, 0,
			"vin0_d5_ti811x", NULL, "pr1_edio_sof_mux1", NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D6, 0,
			"vin0_d6_ti811x", NULL, "pr1_mdio_mdclk_mux1", NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D7, 0,
			"vin0_d7_ti811x", NULL, "pr1_mdio_data_mux1", NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D8, 0,
			"vin0_d8_ti811x", NULL, "pr1_mii_mt1_clk_mux1",
			NULL, NULL, NULL, NULL,	NULL, "vin0b_d_0_mux0", NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D9, 0,
			"vin0_d9_ti811x", NULL, "pr1_mii1_txd3_mux1", NULL,
			NULL, NULL, NULL, NULL, "vin0b_d_1_mux0", NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VIN0_D10, 0,
			"vin0_d10_ti811x", NULL, "pr1_mii1_txd2_mux1", NULL,
			NULL, NULL, NULL, "gpio2_15", "vin0b_d_2_mux0", NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D11, 0,
			"vin0_d11_ti811x", NULL, "pr1_mii1_txd1_mux1", NULL,
			NULL, NULL, NULL, NULL, "vin0b_d_3_mux0", NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VIN0_D12, 0,
			"vin0_d12_ti811x", NULL, "pr1_mii1_txd0_mux1",
			"pr1_pru1_pru_r31_16", "uart7_rtsn_mux0", NULL,
			"pr1_pru1_pru_r30_16", NULL, "vin0b_d_4_mux0", NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D13, 0,
			"vin0_d13_ti811x", NULL, "pr1_mii1_rxd3_mux1",
			"pr1_pru1_pru_r31_20", "uart7_ctsn_mux0", NULL,
			"pr1_pru1_pru_r30_20", NULL, "vin0b_d_5_mux0", NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D14, 0,
			"vin0_d14_ti811x", NULL, "pr1_mii1_rxd2_mux1",
			"pr1_pru1_pru_r31_19", "uart7_rxd_mux0", NULL,
			"pr1_pru1_pru_r30_19", NULL, "vin0b_d_6_mux0", NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D15, 0,
			"vin0_d15_ti811x", NULL, "pr1_mii1_rxd1_mux1",
			"pr1_pru1_pru_r31_18", "uart7_txd_mux0", NULL,
			"pr1_pru1_pru_r30_18", NULL, "vin0b_d_7_mux0", NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D16, 0,
			"vin0_d16_ti811x", NULL, "pr1_mii1_rxd0_mux1",
			"pr1_pru1_pru_r31_17", NULL, NULL,
			"pr1_pru1_pru_r30_17", NULL, "vin0b_d_0_mux1", NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VIN0_D17, 0,
			"vin0_d17_ti811x", NULL, "pr1_mii_mr1_clk_mux1", NULL,
			NULL, NULL, NULL, NULL, "vin0b_d_1_mux1", NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VIN0_D18, 0,
			"vin0_d18_ti811x", NULL, "pr1_mii1_col_mux1", NULL,
			NULL, NULL, NULL, NULL, "vin0b_d_2_mux1", NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VIN0_D19, 0,
			"vin0_d19_ti811x", NULL, "pr1_mii1_rxer_mux1", NULL,
			NULL, NULL, NULL, NULL, "vin0b_d_3_mux1", NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VIN0_D20, 0,
			"vin0_d20_ti811x", NULL, "pr1_mii1_rxdv_mux1", NULL,
			NULL, NULL, NULL, NULL, "vin0b_d_4_mux1", NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VIN0_D21, 0,
			"vin0_d21_ti811x", NULL, "pr1_mii1_txen_mux1", NULL,
			NULL, NULL, NULL, NULL, "vin0b_d_5_mux1", NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VIN0_D22, 0,
			"vin0_d22_ti811x", NULL, "pr1_mii1_rxlink_mux1", NULL,
			NULL, NULL, NULL, NULL, "vin0b_d_6_mux1", NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VIN0_D23, 0,
			"vin0_d23_ti811x", NULL, "pr1_mii1_crs_mux1", NULL,
			NULL, NULL, NULL, NULL, "vin0b_d_7_mux1", NULL, NULL,
			NULL),


	/* No pata modes for DM385, rest all modes valid */
	_TI814X_MUXENTRY(VIN0_DE0_MUX1, 0,
			"vin0_de0_mux1", "cam_d7", NULL, "pata_diorn", NULL,
			NULL, NULL, "gpio0_18_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_DE0_MUX1, 0,
			"vin0_de0_mux1_ti811x", NULL, "vout0_vcom", NULL,
			"uart6_rxd_mux1", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(VIN0_DE1, 0,
			"vin0_de1", "cam_d6", NULL, "pata_csn1", NULL, NULL,
			NULL, "gpio0_19_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_FLD0_MUX1, 0,
			"vin0_fld0_mux1", NULL, "vout0_load1", NULL,
			"uart6_txd_mux1", NULL, NULL, "gpio0_20_mux0", NULL,
			NULL, NULL, NULL),/* for TI811X only */

	/* Following VIN0_FLD0_MUX1 to VOUT0_FID, are not present on TI811X */
	_TI814X_MUXENTRY(VIN0_FLD0_MUX1, 0,
			"vin0_fld0_mux1_ti811x", "cam_d5", NULL, "pata_csn0",
			NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VIN0_FLD1, 0,
			"vin0_fld1", "cam_d4", NULL, "pata_diown", NULL, NULL,
			NULL, "gpio0_21_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC1, 0,
			"vout1_g_y_yc1", "cam_d3", NULL, "pata_dmackn",
			"gpmc_a_5_mux1", "uart4_rxd_mux0", NULL,
			"gpio0_22_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC0, 0,
			"vout1_g_y_yc0", "cam_d2", NULL, "pata_da2",
			"gpmc_a_6_mux1", "uart4_txd_mux0", NULL,
			"gpio0_23_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR1, 0,
			"vout1_r_cr1", "cam_d1", NULL, "pata_da1",
			"gpmc_a_7_mux1", "uart4_ctsn_mux0", NULL,
			"gpio0_24_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR0, 0,
			"vout1_r_cr0", "cam_d0", NULL, "pata_da0",
			"gpmc_a_8_mux1", "uart4_rtsn_mux0", NULL,
			"gpio0_25_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_B_CB_C1, 0,
			"vout1_b_cb_c1", "cam_hs", NULL, "pata_dmarq",
			"gpmc_a_9_mux1", "uart2_rxd_mux0", NULL,
			"gpio0_26_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_B_CB_C0, 0,
			"vout1_b_cb_c0", "cam_vs", NULL, "pata_iordy",
			"gpmc_a_10_mux1", "uart2_txd_mux0", NULL,
			"gpio0_27_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_FID, 0,
			"vout1_fid", "cam_fld", "cam_de_mux0", "pata_intrq",
			"gpmc_a_11_mux1", "uart2_ctsn", NULL, "gpio0_28_mux0",
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_FID, 0,
			"vout0_fid_mux1", "cam_pclk", NULL, "pata_resetn",
			"gpmc_a_12_mux1", "uart2_rtsn", NULL, "gpio2_02_mux0",
			NULL, NULL, NULL, NULL),

	_TI814X_MUXENTRY(VOUT0_CLK, 0,
			"vout0_clk", NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_HSYNC, 0,
			"vout0_hsync", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_HSYNC, 0,
			"vout0_hsync_ti811x", NULL, NULL, NULL, NULL, NULL,
			NULL, "gpio4_19", NULL, NULL, NULL,
			NULL),/* for TI811X only */
	_TI814X_MUXENTRY(VOUT0_VSYNC, 0,
			"vout0_vsync", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_AVID, 0,
			"vout0_avid", "vout0_fid_mux0", NULL, NULL,
			"spi3_sclk_mux2", NULL, "timer7_mux1", "gpio2_21", NULL,
			NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_B_CB_C2, 0,
			"vout0_b_cb_c2", "emu2", NULL, NULL, NULL, NULL, NULL,
			"gpio2_22", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_B_CB_C3, 0,
			"vout0_b_cb_c3", "obs_event0", NULL, NULL, NULL, NULL,
			NULL, "gpio2_23", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_B_CB_C4, 0,
			"vout0_b_cb_c4", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_B_CB_C5, 0,
			"vout0_b_cb_c5", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_B_CB_C6, 0,
			"vout0_b_cb_c6", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_B_CB_C7, 0,
			"vout0_b_cb_c7", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_B_CB_C8, 0,
			"vout0_b_cb_c8", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_B_CB_C9, 0,
			"vout0_b_cb_c9", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_G_Y_YC2, 0,
			"vout0_g_y_yc2", "emu3", NULL, NULL, NULL, NULL, NULL,
			"gpio2_24", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_G_Y_YC3, 0,
			"vout0_g_y_yc3", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio2_25", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_G_Y_YC4, 0,
			"vout0_g_y_yc4", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_G_Y_YC5, 0,
			"vout0_g_y_yc5", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_G_Y_YC6, 0,
			"vout0_g_y_yc6", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_G_Y_YC7, 0,
			"vout0_g_y_yc7", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_G_Y_YC8, 0,
			"vout0_g_y_yc8", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_G_Y_YC9, 0,
			"vout0_g_y_yc9", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_R_CR2, 0,
			"vout0_r_cr2", "emu4", NULL, NULL, NULL, NULL, NULL,
			"gpio2_26", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_R_CR3, 0,
			"vout0_r_cr3", "obs_event1", NULL, NULL, NULL, NULL,
			NULL, "gpio2_27", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_R_CR4, 0,
			"vout0_r_cr4", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_R_CR5, 0,
			"vout0_r_cr5", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_R_CR6, 0,
			"vout0_r_cr6", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_R_CR7, 0,
			"vout0_r_cr7", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_R_CR8, 0,
			"vout0_r_cr8", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_R_CR9, 0,
			"vout0_r_cr9", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),

	/* Following from VOUT0_VSYNC to VOUT0_R_CR9 are on TI811X only */
	_TI814X_MUXENTRY(VOUT0_VSYNC, 0,
			"vout0_vsync_ti811x", NULL, "vout0_load3", NULL, NULL,
			NULL, NULL, "gpio4_20", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT0_B_CB_C2, 0,
			"vout0_b_cb_c2_ti811x", NULL, NULL,
			"pr1_pru1_pru_r30_0", "pr1_pru1_pru_r31_0",
			"ehrpwm1A_mux2", NULL, NULL, NULL, NULL, "hw_dbg0",
			NULL),
	_TI814X_MUXENTRY(VOUT0_B_CB_C3, 0,
			"vout0_b_cb_c3_ti811x", "clkout0_mux1", NULL,
			"pr1_pru1_pru_r30_1", "pr1_pru1_pru_r31_1", NULL,
			"uart6_txd_mux0", NULL, NULL, NULL, "hw_dbg1", NULL),
	_TI814X_MUXENTRY(VOUT0_B_CB_C4, 0,
			"vout0_b_cb_c4_ti811x", NULL, NULL,
			"pr1_pru1_pru_r30_6", "pr1_pru1_pru_r31_6",
			"eQEP2_index_mux1", NULL, "gpio4_21", NULL, "obs_irq0",
			"hw_dbg2", NULL),
	_TI814X_MUXENTRY(VOUT0_B_CB_C5, 0,
			"vout0_b_cb_c5_ti811x", NULL, NULL, NULL, NULL, NULL,
			NULL, "gpio4_22", NULL, "obs_dma0", "hw_dbg3", NULL),
	_TI814X_MUXENTRY(VOUT0_B_CB_C6, 0,
			"vout0_b_cb_c6_ti811x", NULL, NULL, NULL, NULL, NULL,
			NULL, "gpio4_23", NULL, "obs_irq1", "hw_dbg4", NULL),
	_TI814X_MUXENTRY(VOUT0_B_CB_C7, 0,
			"vout0_b_cb_c7_ti811x", NULL, NULL, NULL, NULL, NULL,
			NULL, "gpio4_24", NULL, "obs_dma1", "hw_dbg5", NULL),
	_TI814X_MUXENTRY(VOUT0_B_CB_C8, 0,
			"vout0_b_cb_c8_ti811x", NULL, "pr1_mii_mt0_clk_mux1",
			NULL, NULL, NULL, NULL, "gpio4_25", NULL, NULL,
			"hw_dbg6", NULL),
	_TI814X_MUXENTRY(VOUT0_B_CB_C9, 0,
			"vout0_b_cb_c9_ti811x", NULL, "pr1_mii0_rxlink_mux1",
			NULL, NULL, NULL, NULL, "gpio4_26", NULL, NULL,
			"hw_dbg7", NULL),
	_TI814X_MUXENTRY(VOUT0_G_Y_YC2, 0,
			"vout0_g_y_yc2_ti811x", NULL, "pr1_mii0_col_mux1",
			"pr1_pru1_pru_r30_2", "pr1_pru1_pru_r31_2",
			"ehrpwm1B_mux2", NULL, NULL, NULL, NULL, "hw_dbg8",
			NULL),
	_TI814X_MUXENTRY(VOUT0_G_Y_YC3, 0,
			"vout0_g_y_yc3_ti811x", "eQEP1_strobe_mux1",
			"pr1_mii0_rxer_mux1", "pr1_pru1_pru_r30_3",
			"pr1_pru1_pru_r31_3", "ehrpwm1_tripzone_input_mux2",
			"uart6_rxd_mux0", NULL, NULL, NULL, "hw_dbg9", NULL),
	_TI814X_MUXENTRY(VOUT0_G_Y_YC4, 0,
			"vout0_g_y_yc4_ti811x", NULL, "pr1_mii0_txen_mux1",
			NULL, NULL, NULL, NULL,	"gpio5_10", NULL, NULL,
			"hw_dbg10", NULL),
	_TI814X_MUXENTRY(VOUT0_G_Y_YC5, 0,
			"vout0_g_y_yc5_ti811x", NULL, "pr1_mii0_txd3_mux1",
			NULL, NULL, NULL, NULL,
			"gpio5_11", NULL, NULL, "hw_dbg11", NULL),
	_TI814X_MUXENTRY(VOUT0_G_Y_YC6, 0,
			"vout0_g_y_yc6_ti811x", NULL, "pr1_mii0_txd2_mux1",
			NULL, NULL, NULL, NULL,	"gpio5_12", NULL, NULL,
			"hw_dbg12", NULL),
	_TI814X_MUXENTRY(VOUT0_G_Y_YC7, 0,
			"vout0_g_y_yc7_ti811x", NULL, "pr1_mii0_txd1_mux1",
			NULL, NULL, NULL, NULL,	"gpio5_13", NULL, NULL,
			"hw_dbg13", NULL),
	_TI814X_MUXENTRY(VOUT0_G_Y_YC8, 0,
			"vout0_g_y_yc8_ti811x", NULL, "pr1_mii0_txd0_mux1",
			NULL, NULL, NULL, NULL,	"gpio5_14", NULL, NULL,
			"hw_dbg14", NULL),
	_TI814X_MUXENTRY(VOUT0_G_Y_YC9, 0,
			"vout0_g_y_yc9_ti811x", NULL, "pr1_mii_mr0_clk_mux1",
			NULL, NULL, NULL, NULL,	"gpio5_15", NULL, NULL,
			"hw_dbg15", NULL),
	_TI814X_MUXENTRY(VOUT0_R_CR2, 0,
			"vout0_r_cr2_ti811x", NULL, "pr1_mii0_rxdv_mux1",
			"pr1_pru1_pru_r30_4", "pr1_pru1_pru_r31_4",
			"eQEP2A_in_mux1", "uart6_cts", NULL, NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VOUT0_R_CR3, 0,
			"vout0_r_cr3_ti811x", "clkout1_mux2",
			"pr1_mii0_rxd3_mux1", "pr1_pru1_pru_r30_5",
			"pr1_pru1_pru_r31_5", "eQEP2B_in_mux1", "uart6_rtsn",
			NULL, NULL, NULL, "hw_dbg17", NULL),
	_TI814X_MUXENTRY(VOUT0_R_CR4, 0,
			"vout0_r_cr4_ti811x", NULL, "pr1_mii0_rxd2_mux1",
			"pr1_pru1_pru_r30_7", "pr1_pru1_pru_r31_7",
			"eQEP2_strobe_mux1", NULL, "gpio4_27", NULL, NULL,
			"hw_dbg18", NULL),
	_TI814X_MUXENTRY(VOUT0_R_CR5, 0,
			"vout0_r_cr5_ti811x", NULL, "pr1_mii0_rxd1_mux1", NULL,
			NULL, NULL, NULL, "gpio4_28", NULL, NULL, "hw_dbg19",
			NULL),
	_TI814X_MUXENTRY(VOUT0_R_CR6, 0,
			"vout0_r_cr6_ti811x", NULL, "pr1_mii0_rxd0_mux1", NULL,
			NULL, NULL, NULL, "gpio4_29", NULL, NULL, "hw_dbg20",
			NULL),
	_TI814X_MUXENTRY(VOUT0_R_CR7, 0,
			"vout0_r_cr7_ti811x", NULL, "pr1_mii0_crs_mux1", NULL,
			NULL, NULL, "pr1_mdio_mdclk_mux0", "gpio4_31", NULL,
			NULL, "hw_dbg22", NULL),
	_TI814X_MUXENTRY(VOUT0_R_CR8, 0,
			"vout0_r_cr8_ti811x", NULL, NULL, NULL, NULL, NULL,
			"pr1_mdio_mdclk_mux0", "gpio4_31", NULL, NULL,
			"hw_dbg22", NULL),
	_TI814X_MUXENTRY(VOUT0_R_CR9, 0,
			"vout0_r_cr9_ti811x", NULL, NULL, NULL, NULL, NULL,
			"pr1_mdio_data_mux0", "gpio5_5", NULL, NULL, "hw_dbg23",
			NULL),


	/* pata and uart4/5 modes are not present on DM385, rest available */
	_TI814X_MUXENTRY(VOUT1_CLK, 0,
			"vout1_clk", "gmii1_txclk", "vin1_hsync0",
			"pata_hddir_mux0", NULL, NULL, NULL, "gpio2_28", NULL,
			NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_HSYNC, 0,
			"vout1_hsync", "gmii1_col", "vin1_vsync0",
			"pata_hddir_mux1", "spi3_d_1_mux2", "uart3_rtsn_mux1",
			NULL, "gpio2_29", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_VSYNC, 0,
			"vout1_vsync", "gmii1_crs", "vin1_fid0", "vin1_de0",
			"spi3_d_0_mux2", "uart3_ctsn_mux1", NULL, "gpio2_30",
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_AVID, 0,
			"vout1_avid", "gmii1_rxer", "vin1_clk0", NULL, NULL,
			"uart4_rtsn_mux2", "timer6_mux1", "gpio2_31", NULL,
			NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_B_CB_C3, 0,
			"vout1_b_cb_c3", "gmii1_rxclk", "vin1a_d0", NULL, NULL,
			"uart4_ctsn_mux2", NULL, "gpio3_0", NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VOUT1_B_CB_C4, 0,
			"vout1_b_cb_c4", "gmii1_rxd0", "vin1a_d1", NULL, NULL,
			"uart4_rxd_mux2", NULL, "gpio3_1", NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VOUT1_B_CB_C5, 0,
			"vout1_b_cb_c5", "gmii1_rxd1", "vin1a_d2", NULL, NULL,
			"uart4_txd_mux2", NULL, "gpio3_2", NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VOUT1_B_CB_C6, 0,
			"vout1_b_cb_c6", "gmii1_rxd2", "vin1a_d3", NULL, NULL,
			"uart3_rxd_mux1", NULL, "gpio3_3", NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VOUT1_B_CB_C7, 0,
			"vout1_b_cb_c7", "gmii1_rxd3", "vin1a_d4", NULL, NULL,
			"uart3_txd_mux1", NULL, "gpio3_4", NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VOUT1_B_CB_C8, 0,
			"vout1_b_cb_c8", "gmii1_rxd4", "vin1a_d5", NULL, NULL,
			"i2c3_scl_mux3", NULL, "gpio3_5", NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VOUT1_B_CB_C9, 0,
			"vout1_b_cb_c9", "gmii1_rxd5", "vin1a_d6", NULL, NULL,
			"i2c3_sda_mux3", NULL, "gpio3_6", NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC3, 0,
			"vout1_g_y_yc3", "gmii1_rxd6", "vin1a_d8", "pata_d0",
			NULL, NULL, NULL, "gpio3_7", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC4, 0,
			"vout1_g_y_yc4", "gmii1_rxd7", "vin1a_d9", "pata_d1",
			NULL, NULL, NULL, "gpio3_8", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC5, 0,
			"vout1_g_y_yc5", "gmii1_rxdv", "vin1a_d10", "pata_d2",
			NULL, NULL, NULL, "gpio3_9", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC6, 0,
			"vout1_g_y_yc6", "gmii1_gtxclk", "vin1a_d11", "pata_d3",
			NULL, NULL, NULL, "gpio3_10", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC7, 0,
			"vout1_g_y_yc7", "gmii1_txd0", "vin1a_d12", "pata_d4",
			NULL, NULL, NULL, "gpio3_11", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC8, 0,
			"vout1_g_y_yc8", "gmii1_txd1", "vin1a_d13", "pata_d5",
			NULL, NULL, NULL, "gpio3_12", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC9, 0,
			"vout1_g_y_yc9", "gmii1_txd2", "vin1a_d14", "pata_d6",
			NULL, NULL, NULL, "gpio3_13", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR4, 0,
			"vout1_r_cr4", "gmii1_txd3", "vin1a_d15", "pata_d7",
			NULL, "spi3_cs1", NULL, "gpio3_14", NULL, NULL, NULL,
			NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR5, 0,
			"vout1_r_cr5", "gmii1_txd4", "vin1a_d16", "pata_d8",
			NULL, "spi3_sclk_mux1", NULL, "gpio3_15", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR6, 0,
			"vout1_r_cr6", "gmii1_txd5", "vin1a_d17", "pata_d9",
			NULL, "spi3_d_1_mux1", NULL, "gpio3_16", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR7, 0,
			"vout1_r_cr7", "gmii1_txd6", "vin1a_d18", "pata_d10",
			NULL, "spi3_d_0_mux1", NULL, "gpio3_17", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR8, 0,
			"vout1_r_cr8", "gmii1_txd7", "vin1a_d19", "pata_d11",
			NULL, "uart5_rxd_mux2", NULL, "gpio3_18", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR9, 0,
			"vout1_r_cr9", "gmii1_txen", "vin1a_d20", "pata_d12",
			NULL, "uart5_txd_mux2", NULL, "gpio3_19", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC2, 0,
			"vout1_g_y_yc2", "gpmc_a_13_mux1", "vin1a_d21",
			"pata_d13", "hdmi_ddc_scl_mux1", "spi2_cs2",
			"i2c2_scl_mux2", "gpio3_20", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR3, 0,
			"vout1_r_cr3", "gpmc_a_14_mux1", "vin1a_d22",
			"pata_d14", "hdmi_ddc_sda_mux1", "spi2_sclk_mux1",
			"i2c2_sda_mux2", "gpio3_21", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR2, 0,
			"vout1_r_cr2", "gpmc_a_15_mux1", "vin1a_d23",
			"pata_d15", "hdmi_hpd_mux1", "spi2_d_1_mux1", NULL,
			"gpio3_22", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_B_CB_C2, 0,
			"vout1_b_cb_c2", "gpmc_a_0_mux1", "vin1a_d7", NULL,
			"hdmi_cec_mux1", "spi2_d_0_mux1", NULL,
			"gpio3_30_mux1", NULL, NULL, NULL, NULL),

	/* Following entries , from VOUT1_HSYNC to VOUT1_B_CB_C2,
	 * are for TI811X only
	 */
	_TI814X_MUXENTRY(VOUT1_HSYNC, 0,
			"vout1_hsync_ti811x", NULL, NULL,
			NULL, NULL, NULL,
			"vout1_load0", NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_VSYNC, 0,
			"vout1_vsync_ti811x", NULL, NULL, NULL,
			NULL, NULL, "vout1_load3", NULL, NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_AVID, 0,
			"vout1_avid_ti811x", NULL, NULL, NULL, "vout1_vcom",
			NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_B_CB_C3, 0,
			"vout1_b_cb_c3_ti811x", NULL, NULL,
			"pr1_uart0_cts_n_mux1", NULL, NULL, "vout1_load1",
			"gpio3_0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_B_CB_C8, 0,
			"vout1_b_cb_c8_ti811x", NULL, NULL, NULL,
			"pr1_edio_data_out0", NULL, NULL, NULL, NULL,
			"pr1_edio_data_in0", NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_B_CB_C9, 0,
			"vout1_b_cb_c9_ti811x", NULL, NULL, NULL,
			"pr1_edio_data_out1", NULL, NULL, NULL, NULL,
			"pr1_edio_data_in1", NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC3, 0,
			"vout1_g_y_yc3_ti811x", NULL, NULL, NULL,
			"pr1_edio_data_out2", "pr1_pru1_pru_r30_8",
			"pr1_pru1_pru_r31_8", NULL, NULL, "pr1_edio_data_in2",
			NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC4, 0,
			"vout1_g_y_yc4_ti811x", NULL, NULL, NULL,
			"pr1_edio_data_out3", "pr1_pru1_pru_r30_9",
			"pr1_pru1_pru_r31_9", NULL, NULL, "pr1_edio_data_in3",
			"uart2_rxd_mux4", NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC5, 0,
			"vout1_g_y_yc5_ti811x", NULL, NULL, NULL,
			"pr1_edio_data_out4", "pr1_pru1_pru_r30_10",
			"pr1_pru1_pru_r31_10", NULL, NULL, "pr1_edio_data_in4",
			"uart2_txd_mux4", NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC6, 0,
			"vout1_g_y_yc6_ti811x", NULL, NULL, NULL,
			"pr1_edio_data_out5", "pr1_pru1_pru_r30_11",
			"pr1_pru1_pru_r31_11", NULL, NULL, "pr1_edio_data_in5",
			"uart7_rtsn_mux1", NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC7, 0,
			"vout1_g_y_yc7_ti811x", NULL, NULL, NULL,
			"pr1_edio_data_out6", "pr1_pru1_pru_r30_12",
			"pr1_pru1_pru_r31_12", NULL, NULL, "pr1_edio_data_in6",
			"uart7_ctsn_mux1", NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC8, 0,
			"vout1_g_y_yc8_ti811x", NULL, NULL, NULL,
			"pr1_edio_data_out7", "pr1_pru1_pru_r30_13",
			"pr1_pru1_pru_r31_13", NULL, NULL, "pr1_edio_data_in7",
			"uart7_rxd_mux1", NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC9, 0,
			"vout1_g_y_yc9_ti811x", NULL, NULL, NULL,
			"pr1_edio_sof_mux0", NULL, NULL, NULL, NULL,
			"pr1_uart0_cts_n_mux0",	"uart7_txd_mux1", NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR4, 0,
			"vout1_r_cr4_ti811x", NULL, NULL, NULL,
			"pr1_edio_latch_in", NULL, NULL, NULL, NULL,
			"pr1_uart0_rts_n_mux0", NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR5, 0,
			"vout1_r_cr5_ti811x", NULL, NULL, NULL,	NULL, NULL,
			NULL, NULL, NULL, "pr1_uart0_rxd_mux0",	NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR6, 0,
			"vout1_r_cr6_ti811x", NULL, NULL, NULL,	NULL, NULL,
			NULL, NULL, NULL, "pr1_uart0_txd_mux0",	NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR7, 0,
			"vout1_r_cr7_ti811x", NULL, NULL, NULL,	NULL, NULL,
			NULL, NULL, "pr1_edc_latch0_in_mux0", NULL,
			"timer4_mux4", NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR8, 0,
			"vout1_r_cr8_ti811x", NULL, NULL, NULL,	NULL, NULL,
			NULL, NULL, "pr1_edc_latch1_in_mux0",
			"pr1_uart0_rts_n_mux1", "timer5_mux4", NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR9, 0,
			"vout1_r_cr9_ti811x", NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_G_Y_YC2, 0,
			"vout1_g_y_yc2_ti811x", NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, "pr1_edc_sync0_out_mux0",
			"pr1_uart0_rxd_mux1", NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR3, 0,
			"vout1_r_cr3_ti811x", NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL,	"pr1_edc_sync1_out_mux0",
			"pr1_uart0_txd_mux1", NULL),
	_TI814X_MUXENTRY(VOUT1_R_CR2, 0,
			"vout1_r_cr2_ti811x", NULL, NULL, NULL, NULL, NULL,
			"vout1_load2", NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(VOUT1_B_CB_C2, 0,
			"vout1_b_cb_c2_ti811x", NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL, NULL),


	_TI814X_MUXENTRY(RMII_REFCLK, 0,
			"rmii_refclk", NULL, NULL, NULL, NULL, NULL,
			"timer2_mux3", "gpio1_10_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MDIO_MCLK, 0,
			"mdio_mclk", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio1_11_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(MDIO_D, 0,
			"mdio_d", NULL, NULL, NULL, NULL, NULL, NULL,
			"gpio1_12_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXCLK, 0,
			"gmii0_txclk", "vin1b_d0", NULL, NULL, NULL, "spi3_cs3",
			"i2c2_sda_mux3", "gpio3_23", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_COL, 0,
			"gmii0_col", "vin1b_d1", "rmii0_rxd0", NULL, NULL, NULL,
			NULL, "gpio3_24", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_CRS, 0,
			"gmii0_crs", "vin1b_d2", "rmii0_rxd1", NULL, NULL, NULL,
			NULL, "gpio3_25", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_RXER, 0,
			"gmii0_rxer", "vin1b_d3", "rmii0_rxer", NULL, NULL,
			NULL, NULL, "gpio3_26", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_RXCLK, 0,
			"gmii0_rxclk", "vin1b_d4", "rmii0_crs", NULL, NULL,
			"spi3_cs2", NULL, "gpio3_27", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_RXD0, 0,
			"gmii0_rxd0", "vin1b_d5", "rmii0_txd0", NULL, NULL,
			NULL, NULL, "gpio3_28", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_RXD1, 0,
			"gmii0_rxd1", "vin1b_d6", "rmii0_txd1", NULL, NULL,
			NULL, NULL, "gpio3_29", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_RXD2, 0,
			"gmii0_rxd2", "vin1b_d7", "rmii0_txen", NULL, NULL,
			NULL, NULL, "gpio3_30_mux0", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_RXD3, 0,
			"gmii0_rxd3", NULL, "gpmc_a_27_mux1", "gpmc_a_26_mux1",
			"gpmc_a_0_mux0", "uart5_rxd_mux0", NULL, NULL, NULL,
			NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_RXD4, 0,
			"gmii0_rxd4", NULL, NULL, NULL, "gpmc_a_1_mux0",
			"uart5_txd_mux0", NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_RXD5, 0,
			"gmii0_rxd5", NULL, NULL, NULL, "gpmc_a_2_mux0",
			"uart5_ctsn_mux0", NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_RXD6, 0,
			"gmii0_rxd6", NULL, NULL, NULL, "gpmc_a_3_mux0",
			"uart5_rtsn_mux0", NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_RXD7, 0,
			"gmii0_rxd7", NULL, NULL, NULL, "gpmc_a_4_mux0",
			"spi2_cs3", NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_RXDV, 0,
			"gmii0_rxdv", NULL, NULL, NULL, "gpmc_a_5_mux0",
			"spi2_sclk_mux2", NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_GTXCLK, 0,
			"gmii0_gtxclk", NULL, NULL, NULL, "gpmc_a_6_mux0",
			"spi2_d_1_mux2", NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXD0, 0,
			"gmii0_txd0", NULL, NULL, NULL, "gpmc_a_7_mux0",
			"spi2_d_0_mux2", NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXD1, 0,
			"gmii0_txd1", NULL, NULL, NULL, "gpmc_a_8_mux0",
			"uart4_rxd_mux1", NULL, NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXD2, 0,
			"gmii0_txd2", "rmii1_rxd0_mux0", NULL, NULL,
			"gpmc_a_9_mux0", "uart4_txd_mux1", NULL, NULL, NULL,
			NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXD3, 0,
			"gmii0_txd3", "rmii1_rxd1_mux0", NULL, NULL,
			"gpmc_a_10_mux0", "uart4_ctsn_mux1", NULL, NULL, NULL,
			NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXD4, 0,
			"gmii0_txd4", "rmii1_rxer_mux0", NULL, NULL,
			"gpmc_a_11_mux0", "uart4_rtsn_mux1", NULL, NULL, NULL,
			NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXD5, 0,
			"gmii0_txd5", "rmii1_crs_mux0", NULL, NULL,
			"gpmc_a_12_mux0", "uart1_rxd_mux1", NULL, NULL, NULL,
			NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXD6, 0,
			"gmii0_txd6", "rmii1_txd0_mux0", NULL, NULL,
			"gpmc_a_13_mux0", "uart1_txd_mux1", NULL, NULL, NULL,
			NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXD7, 0,
			"gmii0_txd7", "rmii1_txd1_mux0", NULL, NULL,
			"gpmc_a_14_mux0", "uart1_ctsn", NULL, NULL, NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXEN, 0,
			"gmii0_txen", "rmii1_txen_mux0", NULL, NULL,
			"gpmc_a_15_mux0", "uart1_rtsn", NULL, NULL, NULL, NULL,
			NULL, NULL),

	/* Following GMII0_RXD3 to GMII0_TXEN  are on TI811X only */
	_TI814X_MUXENTRY(GMII0_RXD3, 0,
			"gmii0_rxd3_ti811x", NULL, NULL, NULL,
			NULL, NULL, NULL, "gpio5_16", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_RXD4, 0,
			"gmii0_rxd4_ti811x", NULL, NULL, NULL, NULL,
			NULL, NULL, "gpio5_17", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_RXD5, 0,
			"gmii0_rxd5_ti811x", NULL, NULL, NULL, NULL,
			NULL, NULL, "gpio5_18", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_RXD6, 0,
			"gmii0_rxd6_ti811x", NULL, NULL, NULL, NULL,
			NULL, NULL, "gpio5_19", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_RXD7, 0,
			"gmii0_rxd7_ti811x", NULL, NULL, NULL, NULL,
			NULL, NULL, "gpio5_20", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_RXDV, 0,
			"gmii0_rxdv_ti811x", NULL, NULL, NULL, NULL,
			NULL, NULL, "gpio5_21", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_GTXCLK, 0,
			"gmii0_gtxclk_ti811x", NULL, NULL, NULL, NULL,
			NULL, NULL, "gpio5_22", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXD0, 0,
			"gmii0_txd0_ti811x", NULL, NULL, NULL, NULL,
			NULL, NULL, "gpio5_23", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXD1, 0,
			"gmii0_txd1_ti811x", NULL, NULL, NULL, NULL,
			NULL, NULL, "gpio5_24", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXD2, 0,
			"gmii0_txd2_ti811x", NULL, NULL, NULL,
			NULL, NULL, "ehrpwm2A_mux1", "gpio5_25", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXD3, 0,
			"gmii0_txd3", NULL, NULL, NULL,
			NULL, NULL, "ehrpwm2B_mux1", "gpio5_26", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXD4, 0,
			"gmii0_txd4_ti811x", NULL, NULL, NULL,
			NULL, NULL, "ehrpwm2_tripzone_input_mux1", "gpio5_27",
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXD5, 0,
			"gmii0_txd5_ti811x", NULL, NULL, NULL,
			NULL, NULL, NULL, "gpio5_28", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXD6, 0,
			"gmii0_txd6_ti811x", NULL, NULL, NULL,
			NULL, NULL, "eQEP1A_in_mux1", "gpio5_29", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXD7, 0,
			"gmii0_txd7_ti811x", NULL, NULL, NULL,
			NULL, NULL, "eQEP1B_in_mux1", "gpio5_30", NULL, NULL,
			NULL, NULL),
	_TI814X_MUXENTRY(GMII0_TXEN, 0,
			"gmii0_txen_ti811x", NULL, NULL, NULL,
			NULL, NULL, "eQEP1_index_mux1", "gpio5_31", NULL, NULL,
			NULL, NULL),

	_TI814X_MUXENTRY(CLKIN32, 0,
			"clkin32", NULL, "clkout0", NULL, NULL, NULL,
			"timer3_mux3", "gpio3_31", NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(RESETN, 0,
			"resetn", NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(NMIN, 0,
			"nmin", NULL, NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(RSTOUTN, 0,
			"rstoutn", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(I2C0_SCL, 0,
			"i2c0_scl", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(I2C0_SDA, 0,
			"i2c0_sda", NULL, NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	_TI814X_MUXENTRY(USB_DRVVBUS, 0,
			"usb0_drvvbus", "gpio0_7", NULL, NULL, NULL, NULL, NULL,
			NULL, NULL, NULL, NULL, NULL),
	{ .reg_offset = OMAP_MUX_TERMINATOR },
};

int __init ti814x_mux_init(struct omap_board_mux *board_subset)
{
	return omap_mux_init("core", OMAP_MUX_REG_32BIT,
			TI81XX_CONTROL_PADCONF_MUX_PBASE,
			TI814X_CONTROL_PADCONF_MUX_SIZE, ti814x_muxmodes, NULL,
			board_subset, NULL);
}
#else
int __init ti814x_mux_init(struct omap_board_mux *board_subset)
{
	return 0;
}
#endif
