#
# Makefile for the ti81xx video output device drivers.
#
# TI81XX Display driver
obj-$(CONFIG_VIDEO_TI81XX_VIDOUT) += ti81xxvo.o
ti81xxvo-y := ti81xxvid_main.o
# Makefile for the TI81xx HDVPSS capture driver.
#

obj-$(CONFIG_VIDEO_TI81XX_VIDIN) += ti81xxvin.o

ti81xxvin-y := ti81xxvin_main.o ti81xxvin_lib.o
